"""Add study_time to QuizAttempt and create ChatMessage table

Revision ID: xxxxxxxxxxxx
Revises: <previous-revision-id>
Create Date: 2025-11-13 18:52:20.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Use postgresql or sqlite depending on your DB

# revision identifiers, used by Alembic.
revision = 'xxxxxxxxxxxx'
down_revision = '<previous-revision-id>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add study_time column to the QuizAttempt table
    op.add_column('quiz_attempt', sa.Column('study_time', sa.Integer(), nullable=True))
    # Note: Setting nullable=True and no default is safer for existing data.
    # If you want it NOT NULL, you must set a default value, e.g., sa.Column('study_time', sa.Integer(), nullable=False, server_default=sa.text('0'))

    # 2. Create the ChatMessage table
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop the ChatMessage table
    op.drop_table('chat_message')

    # 2. Remove study_time column from the QuizAttempt table
    op.drop_column('quiz_attempt', 'study_time')

    # ### end Alembic commands ###